apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderprocessing
  labels:
    app: orderprocessing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderprocessing
  template:
    metadata:
      labels:
        app: orderprocessing
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "orderprocessing"
        dapr.io/app-port: "3000"
        dapr.io/config: "appconfig" # Referencing the central config
    spec:
      containers:
        - name: orderprocessing
          image: orderprocessing-service:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: orderprocessing
spec:
  type: LoadBalancer
  selector:
    app: orderprocessing
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000